// Copyright 2024 Ming-Gih Lam (@dcpedit)
/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once
#define VIAL_KEYBOARD_UID {0x3D, 0x36, 0x94, 0xF9, 0x71, 0x35, 0x9D, 0x7E}

#define AUDIO_INIT_DELAY
#define AUDIO_PIN A10
#define AUDIO_PWM_DRIVER PWMD1
#define AUDIO_PWM_CHANNEL 3
#define AUDIO_PWM_PAL_MODE 1

// #define PITCH_STANDARD_A 216.0f
// #define TEMPO_DEFAULT 100
// #define STARTUP_SONG SONG(STARTUP_SOUND)
// #define AUDIO_VOICES

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 10000

#define LED_ACTIVE_LOW
#define LED_NUM_LOCK_PIN A0
#define LED_SCROLL_LOCK_PIN A1
#define LED_LAYER_PIN A2
#define LED_CAPS_LOCK_PIN B9
#define LED_WAIT 100

#define BASE_LAYER 0
#define NUM_LAYER 1
#define MEDIA_LAYER 2
#define SYMBOL_LAYER 3
#define MISC_LAYER 4
#define QWERTY_LAYER 5

#define CUSTOM_MATRIX 1

#define BETTER_VISUAL_MODE
#define VIM_G_MOTIONS
#define VIM_I_TEXT_OBJECTS
#define VIM_A_TEXT_OBJECTS
#define VIM_PASTE_BEFORE
#define VIM_W_BEGINNING_OF_WORD
#define ONESHOT_VIM

